[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_DASHBOARD_URL = "https://app.ally360.co"
  NEXT_PUBLIC_LOGIN_URL = "https://auth.ally360.co/login"
  NEXT_PUBLIC_REGISTER_URL = "https://auth.ally360.co/register"

# Redirecciones para formularios de contacto
[[redirects]]
  from = "/contact"
  to = "/contacto"
  status = 301

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para API
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    
# Configuración específica para formularios de Netlify
[forms]
  # Habilitar procesamiento de formularios
  enabled = true
