[build]
  # Comando de build
  command = "npm run build"
  
  # Node.js version
  node_bundler = "esbuild"

[build.environment]
  # Node.js version para el build
  NODE_VERSION = "20"
  
  # Optimizaciones para Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  
  # No usar NODE_ENV=production aquí para permitir devDependencies
  # NODE_ENV = "production"

# Plugin de Next.js para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirecciones para API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200
  
# Redirecciones para formularios de Netlify
[[redirects]]
  from = "/contact"
  to = "/contacto"
  status = 301
  
# Manejo de SPA para rutas client-side
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para API
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    
# Configuración específica para formularios de Netlify
[forms]
  # Habilitar procesamiento de formularios
  enabled = true
